name: kalkulator_walutowy
description: Produkcyjna aplikacja mobilna Kalkulator Walutowy.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.0
  dio: ^5.4.0
  connectivity_plus: ^6.0.3
  fl_chart: ^0.66.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  collection: ^1.18.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.1.3


 dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/flags/colored/
    - assets/flags/mono/
    - assets/fixtures/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: MonoIcons
      fonts:
        - asset: assets/fonts/MonoIcons.ttf
