name: kalkulator_walutowy
description: "Kalkulator Walutowy – aplikacja mobilna do przeliczania i analizy kursów"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.2
  fl_chart: ^0.66.0
  sqflite: ^2.3.0
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.1.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  provider: ^6.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/flags/
    - assets/fonts/
