name: kalkulator_walutowy
description: Produkcyjna aplikacja mobilna Kalkulator Walutowy.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.2
  fl_chart: ^0.66.0
  sqflite: ^2.3.0
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.1.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/flags/
    - assets/mono_flags/
