name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Guard Android v2
        run: |
          set -e
          # TYLKO twarde markery v1 (bez fałszywych trafień na komentarze/plik nazwany "GeneratedPluginRegistrant.java"):
          ! grep -RInE 'io\.flutter\.app\.FlutterActivity|io\.flutter\.app\.FlutterApplication|GeneratedPluginRegistrant\.registerWith' android \
            || (echo 'Found Android v1 embedding markers' && exit 1)
          # Sanity-check struktury projektu:
          grep -q 'project_type: app' .metadata || (echo '.metadata project_type != app' && exit 1)
          grep -q ':app' android/settings.gradle.kts || (echo 'settings.gradle.kts lacks :app include' && exit 1)
          grep -q 'com.android.application' android/app/build.gradle.kts || (echo 'build.gradle.kts not applying application plugin' && exit 1)

      - name: flutter pub get
        run: flutter pub get

      - name: flutter gen-l10n
        run: flutter gen-l10n

      - name: flutter analyze
        run: flutter analyze

      - name: flutter test (with coverage)
        run: flutter test --coverage

  build_apk:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache build deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Pub get + gen-l10n
        run: |
          flutter pub get
          flutter gen-l10n

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
          compression-level: 0

      - name: Build APK (release, unsigned)
        run: flutter build apk --release

      - name: Upload APK (release-unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          compression-level: 0
